### ISSUE TITLE
CFG scale(guidance scale) for generation

### ISSUE THREAD

**Issue by CiaoHe** [cvlab-columbia/zero123#18]
Hi, when playing with the demo live, I found increase the default CFG(scale) will enhance the generated samples quality (less variance and shaper, like increase it to 10+)
![image](https://user-images.githubusercontent.com/39040787/227825329-649a45a0-ba53-423e-8740-6d12b031dbf0.png)

Just curious about this

**Comment by ruoshiliu** [comment]
Yes, that’s an expected behavior of tuning classifier free guidance scale of diffusion models. Higher cfg scale produces less diversity and higher consistency with input observation, which is not necessarily a good thing depending on application. For single view novel view synthesis, which is a severely under constrained task, similar to text to image generation, diffusion model as a probabilistic image to image translation model is particularly apt as an architecture.
