### ISSUE TITLE
Where is valid_paths.json

### ISSUE THREAD

**Issue by wzic** [cvlab-columbia/zero123#22]
Hi! Happy to read about your excellent work!

May I know where is the file valid_paths.json that is used for training on objaverse? I can only find object-paths.json in the downloaded files.

Thanks.

**Comment by ruoshiliu** [comment]
Hi @wzic , a few hundreds (or thousands) of our downloaded files are corrupted or didn't render correctly, so I created a valid_paths.json to store the path to valid rendering folders.

**Comment by wzic** [comment]
Then what's the content in valid_paths.json? Is it a list of the ids of the objects?

**Comment by ojmichel** [comment]
@wzic From what I can tell it is just a list of the valid object uids in json

**Comment by buttomnutstoast** [comment]
@ruoshiliu , it'd be very helpful if you can release the `valid_paths.json` file, otherwise, we are not able to know which objects are used for training/validation.

**Comment by ruoshiliu** [comment]
[valid_paths.json.zip](https://github.com/cvlab-columbia/zero123/files/11133757/valid_paths.json.zip)
There you go!

**Comment by VitorGuizilini-TRI** [comment]
Hi, can you explain in more details how the evaluation is performed? More specifically, how do you choose which image you use as context, and which ones you use for novel view synthesis?

**Comment by ruoshiliu** [comment]
For GSO and RTMV, we render a bunch of views whose camera poses are randomly sampled. We use the first view as input and the following views for evaluation. Since all views are uniformly sampled, the order doesn't make a difference. Same applies for Objaverse but since our paper focuses on zero-shot performance, we did not run evaluation on objaverse which is our training dataset.
